<a href="https://colab.research.google.com/github/Joss5499/Ejercicios/blob/main/EjerciciosBasicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Libreria - Ciencia de datos

In [1]:
import numpy as np
!pip install numpy

Array de 1 Dimension

In [3]:
array_id = np.array([10, 20, 30])
print(array_id)

[10 20 30]


In [4]:
array_id

array([10, 20, 30])

Array de 2 Dimensiones

In [7]:
array_2d = np.array([(10, 20, 30), (50, 60, 70)])  # Las dos filas tienen 3 elementos
print(array_2d)

[[10 20 30]
 [50 60 70]]


Array de tres Dimensiones

In [9]:
array_3d = np.array([[[1, 2, 3], [5, 6, 7], [9, 10, 11]],
                     [[13, 14, 15], [17, 18, 19], [21, 22, 23]]],dtype=float)

print(array_3d)

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]]

 [[13 14 15]
  [17 18 19]
  [21 22 23]]]


Array con 0 y de 3 filas y 4 columnas

In [10]:
array_zeros = np.zeros((3, 4))

print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array con 1  de 4 filas y 5 columnas

In [11]:
array_ones = np.ones((4, 5))

print(array_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Array con intervalos y saltos

In [12]:
array_intervalos = np.arange(0, 20, 2)

print(array_intervalos)

[ 0  2  4  6  8 10 12 14 16 18]


array de rango de edad de 15 a 30 años cuales son los numeros primos

In [15]:
import numpy as np

# Rango de edades de 15 a 30
rango_edades = np.arange(15, 31)

# Funcion para verificar si un nmero es primo
def es_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):  # solo necesitamos verificar hasta la raiz cuadrada de n
        if n % i == 0:
            return False
    return True

# Filtrar los numeros primos en el rango de edades y convertirlos a enteros normales de Python
numeros_primos = [int(edad) for edad in rango_edades if es_primo(edad)]

print("Números primos en el rango de 15 a 30:", numeros_primos)


Números primos en el rango de 15 a 30: [17, 19, 23, 29]


Array con intervalos y divisiones

In [16]:
import numpy as np

# Crear un array con 5 números igualmente espaciados entre 0 y 1
array_intervalos_divisiones = np.linspace(0, 1, 5)

print(array_intervalos_divisiones)


[0.   0.25 0.5  0.75 1.  ]


array con matriz identidad, diagonal de unos

In [17]:
import numpy as np

# Crear una matriz identidad de 3x3
matriz_identidad = np.eye(3, dtype=int)

print(matriz_identidad)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


array con matriz identidad. diagonal de ceros

In [18]:
import numpy as np

# para una matriz 4x4 de unos
matriz = np.ones((4, 4), dtype=int)

# para rellenar la diagonal con ceros
np.fill_diagonal(matriz, 0)

print(matriz)

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


array  valores aleatorios de 0 - 1

In [21]:
import numpy as np

# Crear un array 1D de 5 valores aleatorios entre 0 y 1
array_aleatorio_1d = np.random.rand(5)

print(array_aleatorio_1d)


[0.49727553 0.88997752 0.6838338  0.81449935 0.4983308 ]


array de numeros vacios de 4x3

In [22]:
import numpy as np

# Crear un array vacío de 4x3
array_vacio = np.empty((4, 3))

print(array_vacio)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
