<a href="https://colab.research.google.com/github/Joss5499/Ejercicios/blob/main/EjerciciosBasicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Libreria - Ciencia de datos

In [9]:
import numpy as np
!pip install numpy

Array de 1 Dimension

In [10]:
array_id = np.array([10, 20, 30])
print(array_id)

[10 20 30]


In [11]:
array_id

array([10, 20, 30])

Array de 2 Dimensiones

In [12]:
array_2d = np.array([(10, 20, 30), (50, 60, 70)])  # Las dos filas tienen 3 elementos
print(array_2d)

[[10 20 30]
 [50 60 70]]


Array de tres Dimensiones

In [13]:
array_3d = np.array([[[1, 2, 3], [5, 6, 7], [9, 10, 11]],
                     [[13, 14, 15], [17, 18, 19], [21, 22, 23]]],dtype=float)

print(array_3d)

[[[ 1.  2.  3.]
  [ 5.  6.  7.]
  [ 9. 10. 11.]]

 [[13. 14. 15.]
  [17. 18. 19.]
  [21. 22. 23.]]]


Array con 0 y de 3 filas y 4 columnas

In [14]:
array_zeros = np.zeros((3, 4))

print(array_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Array con 1  de 4 filas y 5 columnas

In [ ]:
array_ones = np.ones((4, 5))

print(array_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Array con intervalos y saltos

In [ ]:
array_intervalos = np.arange(0, 20, 2)

print(array_intervalos)

[ 0  2  4  6  8 10 12 14 16 18]


array de rango de edad de 15 a 30 años cuales son los numeros primos

In [ ]:
import numpy as np

# Rango de edades de 15 a 30
rango_edades = np.arange(15, 31)

# Funcion para verificar si un nmero es primo
def es_primo(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):  # solo necesitamos verificar hasta la raiz cuadrada de n
        if n % i == 0:
            return False
    return True

# Filtrar los numeros primos en el rango de edades y convertirlos a enteros normales de Python
numeros_primos = [int(edad) for edad in rango_edades if es_primo(edad)]

print("Números primos en el rango de 15 a 30:", numeros_primos)


Números primos en el rango de 15 a 30: [17, 19, 23, 29]


Array con intervalos y divisiones

In [ ]:
import numpy as np

# Crear un array con 5 números igualmente espaciados entre 0 y 1
array_intervalos_divisiones = np.linspace(0, 1, 5)

print(array_intervalos_divisiones)


[0.   0.25 0.5  0.75 1.  ]


array con matriz identidad, diagonal de unos

In [ ]:
import numpy as np

# Crear una matriz identidad de 3x3
matriz_identidad = np.eye(3, dtype=int)

print(matriz_identidad)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


array con matriz identidad. diagonal de ceros

In [ ]:
import numpy as np

# para una matriz 4x4 de unos
matriz = np.ones((4, 4), dtype=int)

# para rellenar la diagonal con ceros
np.fill_diagonal(matriz, 0)

print(matriz)

[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


array  valores aleatorios de 0 - 1

In [ ]:
import numpy as np

# Crear un array 1D de 5 valores aleatorios entre 0 y 1
array_aleatorio_1d = np.random.rand(5)

print(array_aleatorio_1d)


[0.49727553 0.88997752 0.6838338  0.81449935 0.4983308 ]


array de numeros vacios de 4x3

In [ ]:
import numpy as np

# Crear un array vacío de 4x3
array_vacio = np.empty((4, 3))

print(array_vacio)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


grabar y cargar

In [ ]:
#grabar
np.save('mi_array_3d',array_3d)

In [ ]:
#cargar
# Cargar el array guardado en 'mi_array.npy'
mi_array = np.load('mi_array_3d.npy')  # Asegúrate de que el archivo esté en la misma carpeta o da la ruta completa

# Mostrar el array cargado
print(mi_array)

[[0.41512497 0.10308736 0.84842414]
 [0.05891304 0.7845477  0.12712077]
 [0.17822409 0.78630247 0.7548979 ]]


grabar y cargar 2d

In [ ]:
np.save('mi_array_2d',array_2d)

In [ ]:
# Cargar el array guardado en 'mi_array.npy'
mi_array = np.load('mi_array_2d.npy')  # Asegúrate de que el archivo esté en la misma carpeta o da la ruta completa

# Mostrar el array cargado
print(mi_array)

[[10 20 30]
 [50 60 70]]


GRABAR Y CARGAR FICHEROS DE TEXTO

In [ ]:
#grabarf3
np.savetxt('mi_array.txt',array_2d, delimiter="")

In [ ]:
#cargarf3


Tipos de datos

In [ ]:
#entero
np.int64

In [ ]:
#decimal o flotante
np.float64

In [ ]:
#variable compleja
np.complex64

In [ ]:
#boleanos
np.bool_

In [ ]:
#objetos
np.object_

In [ ]:
#cadena texto
np.strings

In [ ]:
np.bytes_

Proiedades y caracteristicas dentro de un entorno

In [15]:
array_3d.shape

(2, 3, 3)

In [17]:
#longitud
len(array_3d)

2

In [18]:
array_3d.ndim

3

In [26]:
import numpy as np

arrays_5d = []

for i in range(5):
    arr = np.random.rand(2, 3, 4, 5, 6)
    arrays_5d.append(arr)
    print(f"Array {i+1} shape:", arr.shape)


Array 1 shape: (2, 3, 4, 5, 6)
Array 2 shape: (2, 3, 4, 5, 6)
Array 3 shape: (2, 3, 4, 5, 6)
Array 4 shape: (2, 3, 4, 5, 6)
Array 5 shape: (2, 3, 4, 5, 6)


In [27]:
array_5d.ndim

5

In [28]:
array_3d.dtype

dtype('float64')

In [29]:
array_3d.dtype.name

'float64'

In [30]:
#convertir de un tipo a otro tipo de dato
array_3d.astype(int)

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]])

In [35]:
array_3d.astype(int)

array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]])

Operadores matematicos

In [36]:
array_id

array([10, 20, 30])

In [39]:
#array de ejemplos
import numpy as np

array1 = np.random.random((4, 4))  # ¡fíjate que las dimensiones van dentro de una tupla!
print(array1)

[[0.77486936 0.22349721 0.43642992 0.90670623]
 [0.17428421 0.49326319 0.54420689 0.9607405 ]
 [0.53601627 0.36844141 0.34836348 0.0547295 ]
 [0.19206311 0.97738289 0.76250498 0.31968124]]


In [40]:
import numpy as np

array2 = np.random.random((4, 4))  # ¡fíjate que las dimensiones van dentro de una tupla!
print(array2)

[[0.89795974 0.46024714 0.19275178 0.75855813]
 [0.45246812 0.82211069 0.29545951 0.83432534]
 [0.35582529 0.7253976  0.54261066 0.874964  ]
 [0.77786208 0.97005351 0.92000059 0.82064905]]


In [41]:
import numpy as np

array3 = np.random.random((4, 4))  # ¡fíjate que las dimensiones van dentro de una tupla!
print(array3)

[[0.80137906 0.97658669 0.17773483 0.28656252]
 [0.33075301 0.77516672 0.25631976 0.94854728]
 [0.98777405 0.99235491 0.2309786  0.22619634]
 [0.66131304 0.57142583 0.0760265  0.59027778]]


In [42]:
#suma
array4=(array1+array2+array3)
print(array4)

[[2.47420816 1.66033105 0.80691653 1.95182689]
 [0.95750534 2.0905406  1.09598616 2.74361313]
 [1.87961561 2.08619392 1.12195274 1.15588985]
 [1.63123823 2.51886223 1.75853206 1.73060806]]


In [46]:
#otra forma de sumar
array4 = np.add(np.add(array1, array2), array3)
print(array4)


[[2.47420816 1.66033105 0.80691653 1.95182689]
 [0.95750534 2.0905406  1.09598616 2.74361313]
 [1.87961561 2.08619392 1.12195274 1.15588985]
 [1.63123823 2.51886223 1.75853206 1.73060806]]


In [44]:
#resta
array4=(array1-array2-array3)
print(array4)

[[-0.92446944 -1.21333662  0.0659433  -0.13841442]
 [-0.60893692 -1.10401421 -0.00757238 -0.82213212]
 [-0.80758307 -1.3493111  -0.42522579 -1.04643085]
 [-1.24711201 -0.56409645 -0.23352211 -1.09124559]]


In [47]:
#otra forma de resta
array4 = np.subtract(np.subtract(array1, array2), array3)
print(array4)

[[-0.92446944 -1.21333662  0.0659433  -0.13841442]
 [-0.60893692 -1.10401421 -0.00757238 -0.82213212]
 [-0.80758307 -1.3493111  -0.42522579 -1.04643085]
 [-1.24711201 -0.56409645 -0.23352211 -1.09124559]]


In [45]:
#multiplicacion
array4=(array1*array2*array3)
print(array4)

[[0.55760075 0.10045557 0.01495152 0.19709466]
 [0.02608254 0.31434324 0.04121394 0.76032719]
 [0.18839631 0.26522324 0.0436609  0.01083172]
 [0.09879925 0.54177666 0.05333297 0.15485708]]


In [48]:
#division
array4 = np.divide(np.divide(array1, array2), array3)
print(array4)

[[ 1.07679649  0.49724475 12.73924131  4.17117431]
 [ 1.16457179  0.77402199  7.18594645  1.21398041]
 [ 1.52504813  0.51182949  2.77953757  0.2765322 ]
 [ 0.37336557  1.76323083 10.90158382  0.65993817]]


In [49]:
array_exp = np.power(array1, 3)
print(array_exp)

[[4.65249017e-01 1.11639103e-02 8.31272741e-02 7.45417877e-01]
 [5.29388084e-03 1.20015166e-01 1.61172935e-01 8.86784922e-01]
 [1.54004680e-01 5.00155809e-02 4.22763852e-02 1.63932256e-04]
 [7.08486977e-03 9.33671696e-01 4.43330945e-01 3.26701742e-02]]


In [50]:
import numpy as np

array1 = np.random.random((4, 4))
array2 = np.random.random((4, 4))


In [51]:
seno_array1 = np.sin(array1)
coseno_array1 = np.cos(array1)

seno_array2 = np.sin(array2)
coseno_array2 = np.cos(array2)

print("Seno de array1:\n", seno_array1)
print("Coseno de array1:\n", coseno_array1)
print("Seno de array2:\n", seno_array2)
print("Coseno de array2:\n", coseno_array2)


Seno de array1:
 [[0.34368307 0.19472915 0.50885405 0.72163162]
 [0.77692039 0.59586987 0.34039349 0.34857968]
 [0.65226207 0.24497117 0.05114747 0.48854818]
 [0.23461591 0.32200726 0.10437258 0.29008484]]
Coseno de array1:
 [[0.9390857  0.98085705 0.86085281 0.69227726]
 [0.62959884 0.803081   0.94028308 0.93727915]
 [0.75799353 0.96953036 0.99869111 0.87253692]
 [0.97208815 0.9467372  0.99453827 0.95700093]]
Seno de array2:
 [[0.59174452 0.69528329 0.62973311 0.7566313 ]
 [0.30428727 0.5881403  0.38038819 0.7444749 ]
 [0.23323158 0.12560655 0.69132868 0.6110109 ]
 [0.59694652 0.78658797 0.83861446 0.76333289]]
Coseno de array2:
 [[0.80612556 0.7187358  0.77681157 0.65384178]
 [0.95258032 0.80875892 0.92482692 0.66765045]
 [0.97242122 0.99208013 0.72254042 0.79162218]
 [0.80228103 0.61747823 0.54472543 0.64600534]]


Comparaciones de matrices

In [52]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 2], [1, 5]])

comparacion = array1 == array2
print(comparacion)

[[False  True]
 [False False]]


In [53]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[2, 2], [1, 5]])

comparacion = array1 == array2
print(comparacion)
print(array1 != array2)  # Elementos diferentes
print(array1 < array2)   # Elementos donde array1 es menor
print(array1 >= array2)  # Elementos donde array1 es mayor o igual

[[False  True]
 [False False]]
[[ True False]
 [ True  True]]
[[ True False]
 [False  True]]
[[False  True]
 [ True False]]


Estadisticas y funciones

In [54]:
import numpy as np

array6 = np.random.random((5, 5))
print(array6)

[[0.63580349 0.83098867 0.33288382 0.53404241 0.09311925]
 [0.48786961 0.72418754 0.90217455 0.27423426 0.13029746]
 [0.65371139 0.9169957  0.38400952 0.10651831 0.09682894]
 [0.06223848 0.66691715 0.91960757 0.68190992 0.32799707]
 [0.82895388 0.20252393 0.90099417 0.70990655 0.41540637]]


In [55]:
sumatotal=array6.sum()
print(sumatotal)

12.820119996056077


In [56]:
maximo = np.max(array6)
minimo = np.min(array6)
promedio = np.mean(array6)

suma = maximo + minimo + promedio
print("Máximo:", maximo)
print("Mínimo:", minimo)
print("Promedio:", promedio)
print("Suma de máximo + mínimo + promedio:", suma)

Máximo: 0.9196075703791067
Mínimo: 0.06223848019361322
Promedio: 0.512804799842243
Suma de máximo + mínimo + promedio: 1.494650850414963


In [57]:
import numpy as np

array6 = np.random.random((5, 5))
print("Array6:\n", array6)

max_por_fila = np.max(array6, axis=1)
min_por_fila = np.min(array6, axis=1)

print("Máximo por fila:", max_por_fila)
print("Mínimo por fila:", min_por_fila)

Array6:
 [[0.02652895 0.55525688 0.1152955  0.98998886 0.94199021]
 [0.90607246 0.49997372 0.22549601 0.13170497 0.07916599]
 [0.23433449 0.64622259 0.59094536 0.02178434 0.73459955]
 [0.62877381 0.68087772 0.95763456 0.7823023  0.29976098]
 [0.80102114 0.42127675 0.67637682 0.6643943  0.82155913]]
Máximo por fila: [0.98998886 0.90607246 0.73459955 0.95763456 0.82155913]
Mínimo por fila: [0.02652895 0.07916599 0.02178434 0.29976098 0.42127675]


In [58]:
#media aritmetica
import numpy as np

array6 = np.random.random((5, 5))
print("Array6:\n", array6)

media = np.mean(array6)
mediana = np.median(array6)

print("Media (promedio) del array6:", media)
print("Mediana del array6:", mediana)


Array6:
 [[0.62950514 0.05403749 0.61257305 0.5100119  0.89791065]
 [0.31502889 0.33192865 0.40722591 0.04149982 0.21107899]
 [0.99990894 0.19286684 0.84421891 0.65660251 0.85511146]
 [0.8964414  0.85130764 0.00558981 0.81978881 0.21542368]
 [0.31786599 0.35734728 0.27264882 0.08978684 0.20635266]]
Media (promedio) del array6: 0.463682482739816
Mediana del array6: 0.3573472752115159
